### ISSUE TITLE
New Method: select(spec)

### ISSUE THREAD

**Issue by islas27** [islas27/array-ext-exercise#4]

**Comment by islas27** [comment]
@ryanez I have a some questions, what should happen if no spec is sent? Actually, the same question applies to all of the previous methods.

Then, let's supose I have an array like this: `['a', 'b', 'c']`, what should happen if I apply select() to it?What happens if the spec sent has no match, like looking for an inexisting property?

**Comment by ryanez** [comment]
In the case of `select` return a copy of the original array, and please make it clear on docs what the result will be on this scenario.

**Comment by islas27** [comment]
Alright @ryanez, then suppose it receives the name of a member of the object (like 'client', in a 'dev' object), should it ignore it, or return an array made of those things?

```js
[{name: "john", client: "github"}, {name: "jane", client: "microsoft"}].select('client') === ["github", "microsoft"]
```

**Comment by islas27** [comment]
Btw, made the first approach to the problem, check commit 9263065
